export const navItems = [
  { id: 0, title: "جدیدترین ها" },
  { id: 1, title: "زنانه" },
  { id: 2, title: "مردانه" },
  { id: 3, title: "نوجوان" },
  { id: 4, title: "بچگانه" },
  { id: 5, title: "سایز بزرگ" },
  { id: 6, title: "کاکا اسپرت" },
  { id: 7, title: "آرایشی بهداشتی" },
  { id: 8, title: "عطر و ادکلن" },
  { id: 9, title: "لوازم خانه" },
  { id: 10, title: "کی توز" },
  { id: 11, title: " فرهنگ و هنر" },
  { id: 12, title: "برندها" },
  { id: 13, title: "جدیدترین ها" },
  { id: 14, title: "زنانه" },
];
